# Hydra PCI stub kmod for FreeBSD
# Build:  make -C drivers/bsd -f Makefile.kmod
# Install: sudo make -C drivers/bsd -f Makefile.kmod install
# Clean: make -C drivers/bsd -f Makefile.kmod clean

KMOD    = hydra
SRCS    = hydra_pci_stub.c device_if.h bus_if.h pci_if.h
CFLAGS += -I${.CURDIR}/../linux/uapi

.include <bsd.kmod.mk>
