#!/bin/bash
# Continuous Documentation Freshening Daemon
#
# This script watches for changes to documentation files and automatically
# freshens stale docs when their dependencies change.
#
# Usage:
#   # Start in foreground
#   ./scripts/doc_watch_freshen.sh
#
#   # Start in background
#   ./scripts/doc_watch_freshen.sh &
#
#   # With custom interval
#   WATCH_INTERVAL=60 ./scripts/doc_watch_freshen.sh

set -euo pipefail

# Configuration
WATCH_INTERVAL=${WATCH_INTERVAL:-300}  # 5 minutes default
LOG_FILE=${LOG_FILE:-"docs/doc_freshen.log"}
AUTO_COMMIT=${AUTO_COMMIT:-false}

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🔄 Documentation Freshening Daemon"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Watch interval: ${WATCH_INTERVAL}s"
echo "Log file: ${LOG_FILE}"
echo "Auto-commit: ${AUTO_COMMIT}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo

# Initialize log
mkdir -p "$(dirname "$LOG_FILE")"
echo "[$(date -Iseconds)] Doc freshening daemon started" >> "$LOG_FILE"

# Counter for iterations
iteration=0

while true; do
    iteration=$((iteration + 1))
    timestamp=$(date -Iseconds)

    echo "[${timestamp}] Iteration ${iteration}: Checking for stale docs..."

    # Rebuild metadata to catch any changes
    if python3 scripts/doc_touch.py --rebuild-metadata >> "$LOG_FILE" 2>&1; then
        echo "  ✓ Metadata rebuilt"
    else
        echo "  ✗ Failed to rebuild metadata (see log)"
        sleep "$WATCH_INTERVAL"
        continue
    fi

    # Check if any docs are stale
    if python3 scripts/doc_touch.py --check >> "$LOG_FILE" 2>&1; then
        echo "  ✓ All docs fresh"
    else
        echo "  ⚠ Stale docs detected - attempting auto-freshen..."

        # Attempt automatic freshening (Tier 1 only)
        if python3 scripts/doc_freshen.py --auto >> "$LOG_FILE" 2>&1; then
            echo "  ✓ Auto-freshening successful"

            # Rebuild metadata after changes
            python3 scripts/doc_touch.py --rebuild-metadata >> "$LOG_FILE" 2>&1

            # Auto-commit if enabled
            if [ "$AUTO_COMMIT" = "true" ]; then
                if git diff --quiet docs/; then
                    echo "  ℹ No changes to commit"
                else
                    echo "  📝 Auto-committing changes..."
                    git add docs/ >> "$LOG_FILE" 2>&1
                    git commit -m "Auto-freshen stale documentation

Generated by doc_watch_freshen.sh at ${timestamp}

🤖 Generated with Claude Code
" >> "$LOG_FILE" 2>&1
                    echo "  ✓ Changes committed"
                fi
            fi
        else
            echo "  ⚠ Auto-freshening partial/failed (check log)"
        fi

        # Generate AI prompts for remaining stale docs (Tier 2/3)
        if python3 scripts/doc_ai_freshen.py --generate-prompts --confidence 0.7 >> "$LOG_FILE" 2>&1; then
            echo "  📝 AI prompts generated for manual review"
        fi
    fi

    echo "  💤 Sleeping for ${WATCH_INTERVAL}s..."
    echo "[${timestamp}] Iteration ${iteration} complete" >> "$LOG_FILE"
    echo

    sleep "$WATCH_INTERVAL"
done
