#!/usr/bin/env python3
"""
Post AI review suggestions as comments on GitHub pull requests.
"""

import argparse
import os
import requests
from pathlib import Path

def post_pr_comment(pr_number, suggestions_file, token=None):
    """Post AI suggestions as a PR comment."""

    if not os.path.exists(suggestions_file):
        print(f"Suggestions file {suggestions_file} not found")
        return

    with open(suggestions_file, 'r') as f:
        content = f.read()

    if not content.strip() or "No significant issues found" in content:
        print("No suggestions to post")
        return

    # Get repository info from environment
    repo = os.environ.get('GITHUB_REPOSITORY', 'dosadi/hydra')
    token = token or os.environ.get('GITHUB_TOKEN')

    if not token:
        print("No GitHub token available - cannot post comment")
        return

    api_url = f"https://api.github.com/repos/{repo}/issues/{pr_number}/comments"

    comment_body = f"""## 🤖 AI Code Review Suggestions

This automated analysis has identified potential improvements for the changed code:

{content}

---
*This comment was automatically generated by the AI code review workflow.
Please review these suggestions and apply them where appropriate.*"""

    headers = {
        'Authorization': f'token {token}',
        'Accept': 'application/vnd.github.v3+json'
    }

    data = {
        'body': comment_body
    }

    try:
        response = requests.post(api_url, headers=headers, json=data)
        response.raise_for_status()
        print(f"Successfully posted AI review comment to PR #{pr_number}")
    except Exception as e:
        print(f"Failed to post comment: {e}")

def main():
    parser = argparse.ArgumentParser(description='Post AI review comments to GitHub PRs')
    parser.add_argument('--pr', required=True, type=int, help='Pull request number')
    parser.add_argument('--suggestions', required=True, help='Suggestions markdown file')
    parser.add_argument('--token', help='GitHub token (optional, uses GITHUB_TOKEN env var)')

    args = parser.parse_args()
    post_pr_comment(args.pr, args.suggestions, args.token)

if __name__ == '__main__':
    main()